In [1]:
import numpy as np

In [2]:
arr_seq = np.arange(25, dtype=np.uint8).reshape(5, 5)

In [3]:
arr_seq

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]], dtype=uint8)

In [4]:
arr_seq[2:5, :]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]], dtype=uint8)

In [5]:
arr_seq[2:5, 0:3]

array([[10, 11, 12],
       [15, 16, 17],
       [20, 21, 22]], dtype=uint8)